{% set OMERO_VERSION = "5.3.0" %}

package:
  name: python-omero
  version: {{ OMERO_VERSION }}

source:
  fn: OMERO.py-{{ OMERO_VERSION }}-ice36-b58.zip
  url: http://downloads.openmicroscopy.org/omero/{{ OMERO_VERSION }}/artifacts/OMERO.py-{{ OMERO_VERSION }}-ice36-b58.zip
  sha1: b04bac55fd981e9e56e6e101b633c4b9a510f6e7
  
build:
    number: 2
    skip: True  # [py3k]

requirements:
  build:
    - conda-build
    - setuptools
    - python
  run:
    - python
    - zeroc-ice

test:
  imports:
    - omero
    - omero.gateway

about:
  home: http://www.openmicroscopy.org/
  license: GPL 2
  summary: OME (Open Microscopy Environment) develops open-source software and data format standards for the storage and manipulation of biological light microscopy data.
