{% set data = load_setup_py_data(from_recipe_dir=True) %}
{% set OMERO_BUILD = "122" %}

package:
  name: "{{ data.get('name')|lower }}"
  version: "{{ data.get('version') }}"

source:
  url: https://downloads.openmicroscopy.org/omero/{{ data.get('version') }}/artifacts/OMERO.py-{{ data.get('version') }}-ice36-b{{ OMERO_BUILD }}.zip
  sha256: 4a746daf214ad2e738906a57952846a0e6681d228ba64bbd8c27676bca87d8a6

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - zeroc-ice >3.5,<3.7

test:
  imports:
    - omero
    - omero.clients
    - omero.gateway
  commands:
    - omero --help

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 (GPLv2)
  license_family: GPL2
  summary: Client library offering helper methods to access an OMERO server.
  doc_url: https://docs.openmicroscopy.org/omero/latest/

extra:
  recipe-maintainers:
    - ome
