{% set OMERO_VERSION = "5.2.7" %}

package:
  name: python-omero
  version: {{ OMERO_VERSION }}

source:
  fn: OMERO.py-{{ OMERO_VERSION }}-ice36-b40.zip
  url: http://downloads.openmicroscopy.org/omero/{{ OMERO_VERSION }}/artifacts/OMERO.py-{{ OMERO_VERSION }}-ice36-b40.zip
  sha1: 8b85145dd1b30ac5cce7c39ceccce8fb16234ae1
  
build:
    number: 0
    skip: True  # [py3k or osx]

requirements:
  build:
    - conda-build
    - setuptools
    - python
  run:
    - python

test:
  imports:
    - omero

about:
  home: http://www.openmicroscopy.org/
  license: GPL 2
  summary: OME (Open Microscopy Environment) develops open-source software and data format standards for the storage and manipulation of biological light microscopy data.
